package jp.co.nttdata.bcp.domain.repository;

import java.util.List;

import jp.co.nttdata.bcp.domain.model.Accounts;
import jp.co.nttdata.bcp.domain.model.account.AccountSearchList;
import jp.co.nttdata.bcp.domain.model.account.AccountWithVendor;
import jp.co.nttdata.bcp.domain.model.account.AccountsSummary;
import jp.co.nttdata.bcp.domain.model.login.UserAccount;

public interface AccountsMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Wed Aug 28 10:29:12 JST 2024
	 */
	int deleteByPrimaryKey(String accountId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Wed Aug 28 10:29:12 JST 2024
	 */
	int insert(Accounts row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Wed Aug 28 10:29:12 JST 2024
	 */
	int insertSelective(Accounts row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Wed Aug 28 10:29:12 JST 2024
	 */
	Accounts selectByPrimaryKey(String accountId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Wed Aug 28 10:29:12 JST 2024
	 */
	int updateByPrimaryKeySelective(Accounts row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accounts
	 * @mbg.generated  Wed Aug 28 10:29:12 JST 2024
	 */
	int updateByPrimaryKey(Accounts row);

	/**
	 * 主キーをもとにアカウント情報（ベンダ情報付き）を取得
	 * @param accountId アカウントID
	 * @return アカウント情報（ベンダ情報付き）
	 */
	AccountWithVendor selectActiveAccountWithVendorByPrimaryKey(String accountId);

	/**
	 * 主キーと更新件数をもとに、現在有効なアカウント情報を更新し、更新件数をインクリメントする
	 * @param account 更新対象のアカウント情報
	 * @return 更新件数
	 */
	int updateAndIncrementCountByVersion(Accounts account);

	/**
	 * 指定された条件に基づくアカウント一覧の件数を取得
	 * 
	 * @param account アカウント情報
	 * @param userAccount アカウント情報
	 * @return アカウント一覧件数
	 */
	Long countListByOffsetLimitWithAccounts(AccountSearchList account, UserAccount userAccount);

	/**
	 * 指定された条件に基づくアカウント一覧を取得
	 * 
	 * @param account アカウント情報
	 * @param userAccount アカウント情報
	 * @param offset オフセット
	 * @param limit 取得件数
	 * @return アカウント一覧
	 */
	List<Accounts> selectListByOffsetLimitWithAccounts(AccountSearchList account, UserAccount userAccount, int offset,
			int limit);

	/**
	 * アカウント情報を取得
	 * 
	 * @param userAccount アカウント情報
	 * @return アカウント情報
	 */
	AccountsSummary selectAccountsSummary(UserAccount userAccount);

	/**
	 * アカウント管理の楽観的ロックと取得
	 * @param accountId アカウントID
	 * @return アカウント管理
	 */
	Accounts selectByPrimaryKeyRecordLock(String accountId);

	/**
	 * アカウント管理から現在有効なアカウントを取得
	 * @param accountId アカウントID
	 * @return アカウント管理
	 */
	Accounts selectActiveByPrimaryKey(String accountId);

	/**
	 * アカウント管理から現在有効なアカウントを取得（レコードロック情報を設定する）
	 * @param accountId アカウントID
	 * @param lock レコードロックをする場合true
	 * @return アカウント管理
	 */
	Accounts selectActiveByPrimaryKey(String accountId, Boolean lock);

	/**
	 * 主キーをもとに、現在有効(desable_flg=falseの)なアカウント情報を更新する（親ベンダIDはベンダに紐づく親ベンダを取得し更新）
	 * @param account 更新対象のアカウント情報
	 * @return 更新件数
	 */
	int updateActiveByPrimaryKeySelective(Accounts account);

	/**
	 * 主キーをもとにアカウント情報（親ベンダ情報付き）を取得
	 * @param accountId アカウントID
	 * @return アカウント情報（親ベンダ情報付き）
	 */
	AccountWithVendor selectActiveAccountWithParentVendorByPrimaryKey(String accountId);

}