package jp.co.nttdata.bcp.domain.repository;

import jp.co.nttdata.bcp.domain.model.Attachedfiles;

public interface AttachedfilesMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table attachedfiles
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int deleteByPrimaryKey(Long key);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table attachedfiles
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int insert(Attachedfiles row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table attachedfiles
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int insertSelective(Attachedfiles row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table attachedfiles
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	Attachedfiles selectByPrimaryKey(Long key);

	/**
	 * This method was generated by MyBatis Generator.
	 * 入力パラメータがNULL以外の項目を更新する。ただし更新日時は常に現在時刻で更新するため値のセットは不要
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int updateByPrimaryKeySelective(Attachedfiles row);

	/**
	 * This method was generated by MyBatis Generator.
     * すべての項目を更新する。ただし更新日時は常に現在時刻で更新するため値のセットは不要
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int updateByPrimaryKey(Attachedfiles row);
	
	/**
	 * 添付ファイル管理を削除する
	 * @param infoKey お知らせキー
	 */
	int deleteByInfoKey(Long infoKey);

}