package jp.co.nttdata.bcp.domain.repository;

import java.util.List;

import jp.co.nttdata.bcp.domain.model.Infos;
import jp.co.nttdata.bcp.domain.model.info.InfoWithFiles;

public interface InfosMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table infos
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int deleteByPrimaryKey(Long key);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table infos
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int insert(Infos row);

	/**
	 * 値が設定されている項目をINSERTし、_keyを取得する
	 *
	 * @param row 挿入する行データ
	 * @return 挿入行の_keyの値
	 */
	Long insertSelectiveAndGetKey(Infos row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table infos
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	Infos selectByPrimaryKey(Long key);

	/**
	 * This method was generated by MyBatis Generator.
	 * 入力パラメータがNULL以外の項目を更新する。ただし更新日時は常に現在時刻で更新するため値のセットは不要
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int updateByPrimaryKeySelective(Infos row);

	/**
	 * This method was generated by MyBatis Generator.
     * すべての項目を更新する。ただし更新日時は常に現在時刻で更新するため値のセットは不要
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int updateByPrimaryKey(Infos row);

	/**
	 * 指定されたoffset,limitに基づくお知らせ情報一覧を取得
	 * 
	 * @param offset 検索結果のオフセット位置（0相対）
	 * @param limit limit
	 * @return お知らせ情報一覧（添付ファイル付き）
	 */
	List<InfoWithFiles> selectListByOffsetLimitWithFiles(Integer offset, Integer limit);

	/**
	 * お知らせ情報の件数を取得
	 * @param userId ユーザID
	 * @return 件数
	 */
	int selectCount();

	/**
	 * お知らせキーをもとにお知らせ情報を添付ファイル付きで取得
	 * 
	 * @param key お知らせキー
	 * @return お知らせ情報（添付ファイル付き）
	 */
	InfoWithFiles selectByKeyWithFiles(Long key);

	/**
	 * お知らせ管理の楽観的ロックと取得
	 * @param key お知らせキー
	 * @return お知らせ情報
	 */
	Infos selectByPrimaryKeyRecordLock(Long key);

	/**
	 * 掲載期限内のお知らせ情報を取得
	 * 
	 * @return お知らせ情報一覧（添付ファイルデータ以外の添付ファイル付き）
	 */
	List<InfoWithFiles> selectInfoToppageList();

}