package jp.co.nttdata.bcp.domain.repository;

import java.util.List;

import jp.co.nttdata.bcp.domain.model.Links;

public interface LinksMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table links
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int deleteByPrimaryKey(Long key);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table links
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int insert(Links row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table links
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int insertSelective(Links row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table links
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	Links selectByPrimaryKey(Long key);

	/**
	 * This method was generated by MyBatis Generator.
	 * 入力パラメータがNULL以外の項目を更新する。ただし更新日時は常に現在時刻で更新するため値のセットは不要
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int updateByPrimaryKeySelective(Links row);

	/**
	 * This method was generated by MyBatis Generator.
     * すべての項目を更新する。ただし更新日時は常に現在時刻で更新するため値のセットは不要
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int updateByPrimaryKey(Links row);

	/**
	 * 外部リンク一覧取得
	 * @return 取得した外部リンク一覧
	 */
	List<Links> selectAll();
}