package jp.co.nttdata.bcp.domain.repository;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import jp.co.nttdata.bcp.domain.model.Users;
import jp.co.nttdata.bcp.domain.model.login.UserAccount;
import jp.co.nttdata.bcp.domain.model.user.UserWithVendor;

public interface UsersMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table users
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int deleteByPrimaryKey(Long key);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table users
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int insert(Users row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table users
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int insertSelective(Users row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table users
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	Users selectByPrimaryKey(Long key);

	/**
	 * This method was generated by MyBatis Generator.
	 * 入力パラメータがNULL以外の項目を更新する。ただし更新日時は常に現在時刻で更新するため値のセットは不要
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int updateByPrimaryKeySelective(Users row);

	/**
	 * This method was generated by MyBatis Generator.
     * すべての項目を更新する。ただし更新日時は常に現在時刻で更新するため値のセットは不要
	 *
	 * @mbg.generated Wed Aug 14 16:01:55 JST 2024
	 */
	int updateByPrimaryKey(Users row);

	/**
	 * ユーザIDもしくはEmailが一致するユーザを取得する。
	 * 
	 * @param userId
	 * @return
	 */
	UserAccount selectByUserIdOrEmail(String userId);

	/**
	 * ユーザIDをキーとしてパスワードを更新する。
	 *
	 * @mbg.generated Tue Aug 06 10:44:47 JST 2024
	 */
	int updatePasswordByUserId(Users row);

	/**
	 * ユーザIDもしくはEmailが一致するユーザをUserオブジェクトで取得する。
	 * 
	 * @param userId
	 * @return ユーザ情報
	 */
	Users selectIserByUserIdOrEmail(Users row);

	/**
	 * Emaiが一致するユーザをUserオブジェクトで取得する。
	 * @param mailAddress EMAILアドレス
	 * @param isForUpdate 排他取得の場合true
	 * @return ユーザ情報
	 */
	Users selectIserByemailAddress(String mailAddress, boolean isForUpdate);

	/**
	 * ベンダ管理から親ベンダIDを取得してユーザ管理を登録する。
	 * @param user ユーザ情報
	 * @return 更新件数
	 */
	int insertWithSelect(Users user);

	/**
	 * 主キーに一致するユーザ情報（ベンダ情報付き）を取得する。
	 * @param key 主キー
	 * @return ユーザ情報（ベンダ情報付き）
	 */
	UserWithVendor selectByPrimaryKeyWithVendor(Long key);

	/**
	 * 指定された条件に基づくユーザ情報一覧の件数を取得
	 * 
	 * @param user ユーザ一覧取得用
	 * @param userAccount アカウント情報
	 * @return ユーザ情報一覧件数
	 */
	Long countListByOffsetLimitWithUsers(Users user, UserAccount userAccount);
	
	/**
	 * 指定された条件に基づくユーザ情報一覧を取得
	 * 
	 * @param user ユーザ一覧取得用入力フォーム
	 * @param userAccount ログインユーザ情報
	 * @param rowBounds 
	 * @return ユーザ情報一覧
	 */
	List<UserWithVendor> selectListByOffsetLimitWithUsers(Users user, UserAccount userAccount,
			RowBounds rowBounds);

	/**
	 * ユーザ情報の楽観的ロックと取得
	 * @param key ユーザキー
	 * @return ユーザ情報
	 */
	Users selectByPrimaryKeyRecordLock(Long key);

	/**
	 * ベンダ管理から親ベンダIDを取得してユーザ管理を更新
	 * @param user ユーザ情報
	 * @return 更新件数
	 */
	int updateAllWithParentVendor(Users user);
}