package jp.co.nttdata.bcp.domain.repository;

import java.util.List;

import jp.co.nttdata.bcp.domain.model.Vendors;
import jp.co.nttdata.bcp.domain.model.login.UserAccount;

public interface VendorsMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendors
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendors
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	int insert(Vendors row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendors
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	int insertSelective(Vendors row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendors
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	Vendors selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendors
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	int updateByPrimaryKeySelective(Vendors row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vendors
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	int updateByPrimaryKey(Vendors row);

	/**
     * ベンダIDをキーにして、対象ベンダの親ベンダの情報を取得する。
     * @param vendorId ベンダID
     * @return ベンダ管理情報
     */
	Vendors selectParentVendorByVendorId(String vendorId);

	/**
	 * ベンダ一覧を取得する
	 * @param userAccount アカウント情報
	 * @return ベンダ一覧
	 */
	List<Vendors> selectListVendor(UserAccount userAccount);

	/**
	 * ベンダ一覧を取得する（S3バケットは親ベンダの情報を取得）
	 * @param userAccount アカウント情報
	 * @return ベンダ一覧
	 */
	List<Vendors> selectListVendorWithParentS3(UserAccount userAccount);

	/**
     * ベンダIDと親ベンダIDをキーにして、ベンダ情報を取得する。
     * @param vendorId ベンダID
     * @param parentId 親ベンダID
     * @return ベンダ管理情報
     */
	Vendors selectByVendorIdAndParentId(String vendorId, String parentId);
}