package jp.co.nttdata.bcp.domain.model;

import java.util.Date;

public class Accounts {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.account_id
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private String accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.account_name
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private String accountName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.account_address
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private String accountAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.vendor_id
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private String vendorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.parent_id
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private String parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.upload_enable
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private Boolean uploadEnable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.upload_timing
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private Integer uploadTiming;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.backup_capa
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private Integer backupCapa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.used_size
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private Integer usedSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.download_enable
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private Boolean downloadEnable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.lastdate
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private Date lastdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.status
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.error_info
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private String errorInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.soft_version
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private String softVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.local_dir
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private String localDir;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.mail_enable
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private Boolean mailEnable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.version
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.update_date
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.disable_flg
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private Boolean disableFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.accounts.auth_key
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	private String authKey;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.account_id
	 * @return  the value of public.accounts.account_id
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public String getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.account_id
	 * @param accountId  the value for public.accounts.account_id
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setAccountId(String accountId) {
		this.accountId = accountId == null ? null : accountId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.account_name
	 * @return  the value of public.accounts.account_name
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public String getAccountName() {
		return accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.account_name
	 * @param accountName  the value for public.accounts.account_name
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setAccountName(String accountName) {
		this.accountName = accountName == null ? null : accountName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.account_address
	 * @return  the value of public.accounts.account_address
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public String getAccountAddress() {
		return accountAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.account_address
	 * @param accountAddress  the value for public.accounts.account_address
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setAccountAddress(String accountAddress) {
		this.accountAddress = accountAddress == null ? null : accountAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.vendor_id
	 * @return  the value of public.accounts.vendor_id
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public String getVendorId() {
		return vendorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.vendor_id
	 * @param vendorId  the value for public.accounts.vendor_id
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setVendorId(String vendorId) {
		this.vendorId = vendorId == null ? null : vendorId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.parent_id
	 * @return  the value of public.accounts.parent_id
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.parent_id
	 * @param parentId  the value for public.accounts.parent_id
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId == null ? null : parentId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.upload_enable
	 * @return  the value of public.accounts.upload_enable
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public Boolean getUploadEnable() {
		return uploadEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.upload_enable
	 * @param uploadEnable  the value for public.accounts.upload_enable
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setUploadEnable(Boolean uploadEnable) {
		this.uploadEnable = uploadEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.upload_timing
	 * @return  the value of public.accounts.upload_timing
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public Integer getUploadTiming() {
		return uploadTiming;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.upload_timing
	 * @param uploadTiming  the value for public.accounts.upload_timing
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setUploadTiming(Integer uploadTiming) {
		this.uploadTiming = uploadTiming;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.backup_capa
	 * @return  the value of public.accounts.backup_capa
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public Integer getBackupCapa() {
		return backupCapa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.backup_capa
	 * @param backupCapa  the value for public.accounts.backup_capa
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setBackupCapa(Integer backupCapa) {
		this.backupCapa = backupCapa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.used_size
	 * @return  the value of public.accounts.used_size
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public Integer getUsedSize() {
		return usedSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.used_size
	 * @param usedSize  the value for public.accounts.used_size
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setUsedSize(Integer usedSize) {
		this.usedSize = usedSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.download_enable
	 * @return  the value of public.accounts.download_enable
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public Boolean getDownloadEnable() {
		return downloadEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.download_enable
	 * @param downloadEnable  the value for public.accounts.download_enable
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setDownloadEnable(Boolean downloadEnable) {
		this.downloadEnable = downloadEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.lastdate
	 * @return  the value of public.accounts.lastdate
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public Date getLastdate() {
		return lastdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.lastdate
	 * @param lastdate  the value for public.accounts.lastdate
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setLastdate(Date lastdate) {
		this.lastdate = lastdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.status
	 * @return  the value of public.accounts.status
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.status
	 * @param status  the value for public.accounts.status
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.error_info
	 * @return  the value of public.accounts.error_info
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public String getErrorInfo() {
		return errorInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.error_info
	 * @param errorInfo  the value for public.accounts.error_info
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setErrorInfo(String errorInfo) {
		this.errorInfo = errorInfo == null ? null : errorInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.soft_version
	 * @return  the value of public.accounts.soft_version
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public String getSoftVersion() {
		return softVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.soft_version
	 * @param softVersion  the value for public.accounts.soft_version
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setSoftVersion(String softVersion) {
		this.softVersion = softVersion == null ? null : softVersion.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.local_dir
	 * @return  the value of public.accounts.local_dir
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public String getLocalDir() {
		return localDir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.local_dir
	 * @param localDir  the value for public.accounts.local_dir
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setLocalDir(String localDir) {
		this.localDir = localDir == null ? null : localDir.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.mail_enable
	 * @return  the value of public.accounts.mail_enable
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public Boolean getMailEnable() {
		return mailEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.mail_enable
	 * @param mailEnable  the value for public.accounts.mail_enable
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setMailEnable(Boolean mailEnable) {
		this.mailEnable = mailEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.version
	 * @return  the value of public.accounts.version
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.version
	 * @param version  the value for public.accounts.version
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.update_date
	 * @return  the value of public.accounts.update_date
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.update_date
	 * @param updateDate  the value for public.accounts.update_date
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.disable_flg
	 * @return  the value of public.accounts.disable_flg
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public Boolean getDisableFlg() {
		return disableFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.disable_flg
	 * @param disableFlg  the value for public.accounts.disable_flg
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setDisableFlg(Boolean disableFlg) {
		this.disableFlg = disableFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.accounts.auth_key
	 * @return  the value of public.accounts.auth_key
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public String getAuthKey() {
		return authKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.accounts.auth_key
	 * @param authKey  the value for public.accounts.auth_key
	 * @mbg.generated  Tue Dec 03 17:32:05 JST 2024
	 */
	public void setAuthKey(String authKey) {
		this.authKey = authKey == null ? null : authKey.trim();
	}
}