package jp.co.nttdata.bcp.domain.model;

import java.util.Date;

public class Attachedfiles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachedfiles._key
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private Long key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachedfiles.info_key
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private Long infoKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachedfiles.file_name
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachedfiles.file_data
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private String fileData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachedfiles.update_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachedfiles._key
     *
     * @return the value of attachedfiles._key
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public Long getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachedfiles._key
     *
     * @param key the value for attachedfiles._key
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setKey(Long key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachedfiles.info_key
     *
     * @return the value of attachedfiles.info_key
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public Long getInfoKey() {
        return infoKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachedfiles.info_key
     *
     * @param infoKey the value for attachedfiles.info_key
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setInfoKey(Long infoKey) {
        this.infoKey = infoKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachedfiles.file_name
     *
     * @return the value of attachedfiles.file_name
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachedfiles.file_name
     *
     * @param fileName the value for attachedfiles.file_name
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachedfiles.file_data
     *
     * @return the value of attachedfiles.file_data
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public String getFileData() {
        return fileData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachedfiles.file_data
     *
     * @param fileData the value for attachedfiles.file_data
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setFileData(String fileData) {
        this.fileData = fileData == null ? null : fileData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachedfiles.update_date
     *
     * @return the value of attachedfiles.update_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachedfiles.update_date
     *
     * @param updateDate the value for attachedfiles.update_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}