package jp.co.nttdata.bcp.domain.model;

public class Bcpsoft {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bcpsoft.version
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bcpsoft.version
     *
     * @return the value of bcpsoft.version
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bcpsoft.version
     *
     * @param version the value for bcpsoft.version
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }
}