package jp.co.nttdata.bcp.domain.model;

import java.util.Date;

public class Infos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos._key
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private Long key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.start_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.end_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.title
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.article
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private String article;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.version
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.user_id
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.update_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos._key
     *
     * @return the value of infos._key
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public Long getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos._key
     *
     * @param key the value for infos._key
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setKey(Long key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.start_date
     *
     * @return the value of infos.start_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.start_date
     *
     * @param startDate the value for infos.start_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.end_date
     *
     * @return the value of infos.end_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.end_date
     *
     * @param endDate the value for infos.end_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.title
     *
     * @return the value of infos.title
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.title
     *
     * @param title the value for infos.title
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.article
     *
     * @return the value of infos.article
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public String getArticle() {
        return article;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.article
     *
     * @param article the value for infos.article
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setArticle(String article) {
        this.article = article == null ? null : article.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.version
     *
     * @return the value of infos.version
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.version
     *
     * @param version the value for infos.version
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.user_id
     *
     * @return the value of infos.user_id
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.user_id
     *
     * @param userId the value for infos.user_id
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.update_date
     *
     * @return the value of infos.update_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.update_date
     *
     * @param updateDate the value for infos.update_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}