package jp.co.nttdata.bcp.domain.model;

import java.util.Date;

public class Links {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links._key
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private Long key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.title
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.link_text
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private String linkText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.url
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column links.update_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links._key
     *
     * @return the value of links._key
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public Long getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links._key
     *
     * @param key the value for links._key
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setKey(Long key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.title
     *
     * @return the value of links.title
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.title
     *
     * @param title the value for links.title
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.link_text
     *
     * @return the value of links.link_text
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public String getLinkText() {
        return linkText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.link_text
     *
     * @param linkText the value for links.link_text
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setLinkText(String linkText) {
        this.linkText = linkText == null ? null : linkText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.url
     *
     * @return the value of links.url
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.url
     *
     * @param url the value for links.url
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column links.update_date
     *
     * @return the value of links.update_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column links.update_date
     *
     * @param updateDate the value for links.update_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}