package jp.co.nttdata.bcp.domain.model;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users._key
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private Long key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.vendor_id
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private String vendorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.parent_id
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_name
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.mail_address
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private String mailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.admin
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private Boolean admin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.version
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.update_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users._key
     *
     * @return the value of users._key
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public Long getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users._key
     *
     * @param key the value for users._key
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setKey(Long key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.vendor_id
     *
     * @return the value of users.vendor_id
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public String getVendorId() {
        return vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.vendor_id
     *
     * @param vendorId the value for users.vendor_id
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setVendorId(String vendorId) {
        this.vendorId = vendorId == null ? null : vendorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.parent_id
     *
     * @return the value of users.parent_id
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.parent_id
     *
     * @param parentId the value for users.parent_id
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_name
     *
     * @return the value of users.user_name
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_name
     *
     * @param userName the value for users.user_name
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.mail_address
     *
     * @return the value of users.mail_address
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.mail_address
     *
     * @param mailAddress the value for users.mail_address
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress == null ? null : mailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.admin
     *
     * @return the value of users.admin
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public Boolean getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.admin
     *
     * @param admin the value for users.admin
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.version
     *
     * @return the value of users.version
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.version
     *
     * @param version the value for users.version
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.update_date
     *
     * @return the value of users.update_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.update_date
     *
     * @param updateDate the value for users.update_date
     *
     * @mbg.generated Wed Aug 14 16:01:55 JST 2024
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}