package jp.co.nttdata.bcp.domain.model;

import java.util.Date;

public class Vendors {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vendors.id
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vendors.parent_id
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	private String parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vendors.name
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vendors.mail_address
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	private String mailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vendors.s3backet
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	private String s3backet;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vendors.cognito_user_id
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	private String cognitoUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vendors.cognito_access_token
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	private String cognitoAccessToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vendors.permit_password
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	private String permitPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vendors.update_date
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	private Date updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vendors.id
	 * @return  the value of vendors.id
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vendors.id
	 * @param id  the value for vendors.id
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vendors.parent_id
	 * @return  the value of vendors.parent_id
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vendors.parent_id
	 * @param parentId  the value for vendors.parent_id
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId == null ? null : parentId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vendors.name
	 * @return  the value of vendors.name
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vendors.name
	 * @param name  the value for vendors.name
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vendors.mail_address
	 * @return  the value of vendors.mail_address
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public String getMailAddress() {
		return mailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vendors.mail_address
	 * @param mailAddress  the value for vendors.mail_address
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public void setMailAddress(String mailAddress) {
		this.mailAddress = mailAddress == null ? null : mailAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vendors.s3backet
	 * @return  the value of vendors.s3backet
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public String getS3backet() {
		return s3backet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vendors.s3backet
	 * @param s3backet  the value for vendors.s3backet
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public void setS3backet(String s3backet) {
		this.s3backet = s3backet == null ? null : s3backet.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vendors.cognito_user_id
	 * @return  the value of vendors.cognito_user_id
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public String getCognitoUserId() {
		return cognitoUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vendors.cognito_user_id
	 * @param cognitoUserId  the value for vendors.cognito_user_id
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public void setCognitoUserId(String cognitoUserId) {
		this.cognitoUserId = cognitoUserId == null ? null : cognitoUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vendors.cognito_access_token
	 * @return  the value of vendors.cognito_access_token
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public String getCognitoAccessToken() {
		return cognitoAccessToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vendors.cognito_access_token
	 * @param cognitoAccessToken  the value for vendors.cognito_access_token
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public void setCognitoAccessToken(String cognitoAccessToken) {
		this.cognitoAccessToken = cognitoAccessToken == null ? null : cognitoAccessToken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vendors.permit_password
	 * @return  the value of vendors.permit_password
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public String getPermitPassword() {
		return permitPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vendors.permit_password
	 * @param permitPassword  the value for vendors.permit_password
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public void setPermitPassword(String permitPassword) {
		this.permitPassword = permitPassword == null ? null : permitPassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vendors.update_date
	 * @return  the value of vendors.update_date
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vendors.update_date
	 * @param updateDate  the value for vendors.update_date
	 * @mbg.generated  Wed Aug 28 10:53:43 JST 2024
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
}